const actions = {
  'subreddit': {
    'SEARCH_SUBREDDITS': 'SEARCH_SUBREDDITS',
    'SEARCH_SUBREDDITS_ERROR': 'SEARCH_SUBREDDITS_ERROR',
    'SEARCH_SUBREDDITS_SUCCESS': 'SEARCH_SUBREDDITS_SUCCESS',
    'UNSUBSCRIBE_SUBREDDIT': 'UNSUBSCRIBE_SUBREDDIT',
    'SUBSCRIBE_SUBREDDIT': 'SUBSCRIBE_SUBREDDIT',
    'ADD_SUBREDDIT_POSTS': 'ADD_SUBREDDIT_POSTS',
    'REMOVE_SUBREDDIT_POSTS': 'REMOVE_SUBREDDIT_POSTS'
  },

  'post': {
    'FILTER_BY_SUBREDDIT' : 'FILTER_BY_SUBREDDIT',
    'REQUEST_POSTS': 'REQUEST_POSTS',
    'REQUEST_POSTS_SUCCESS': 'REQUEST_POSTS_SUCCESS',
    'REQUEST_POSTS_ERROR': 'REQUEST_POSTS_ERROR',
    'REMOVE_POSTS': 'REMOVE_POSTS',
    'FETCH_HOME_SUBREDDIT_POSTS': 'FETCH_HOME_SUBREDDIT_POSTS',
    'REFRESH_POSTS': 'REFRESH_POSTS'
  }

}

export default actions